CREATE TABLE IF NOT EXISTS tbl_users
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR
);

INSERT INTO tbl_users(name) VALUES ('Ivan');
INSERT INTO tbl_users(name) VALUES ('Alina');
INSERT INTO tbl_users(name) VALUES ('Sasha');