services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile-system
    image: java-app-builder
    restart: "no"
  
  app-builder:
    build:
      context: .
      dockerfile: Dockerfile-build
    image: java-app-build
    depends_on:
      - builder
    volumes:
      - ./java-app/src:/app/src
      - ./java-app/pom.xml:/app/pom.xml
    restart: "no"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile-run
    image: java-app
    depends_on:
      - app-builder
    env_file: java-app/java.env
    ports:
      - "8080:8080"
    restart: unless-stopped