services:
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      - database
    env_file: backend/backend.env
    ports:
      - 8080:8080
  database:
    image: postgres:13.20-alpine3.20
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    env_file: database/database.env
volumes:
  postgres:

    