services:
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      - database
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://database:5432/postgres
    ports:
      - 8080:8080
  database:
    image: postgres:13.20-alpine3.20
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres:

    